server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA por hash-routing: no hacen falta rewrites, todo sirve index.html.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché largo para estáticos versionables
    location /assets/ {
        access_log off;
        expires 7d;
        add_header Cache-Control "public";
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_min_length 512;
}
